name: mensa_upb
description: A mobile app for the Mensa at the University of Paderborn.
funding:
  - https://github.com/sponsors/moritz-hoelting
repository: https://github.com/moritz-hoelting/mensa-upb-app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  provider: ^6.1.5
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  flutter_layout_grid: ^2.0.8
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  toggle_switch: ^2.3.0
  fixed: ^6.1.1

dev_dependencies:
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
